{{- range $val := .Values.classes }}
{{- if $val.storageClass }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $val.name }}
  {{- if kindIs "map" $val.storageClass }}
  {{- if $val.storageClass.isDefaultClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
  {{- end }}
  labels:
    helm.sh/chart: {{ template "provisioner.chart" $ }}
    app.kubernetes.io/name: {{ template "provisioner.name" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
{{- if kindIs "map" $val.storageClass }}
provisioner: {{ $val.storageClass.provisioner | default "kubernetes.io/no-provisioner" }}
{{- else }}
provisioner: kubernetes.io/no-provisioner
{{- end }}
volumeBindingMode: WaitForFirstConsumer
{{- if kindIs "map" $val.storageClass }}
reclaimPolicy: {{ $val.storageClass.reclaimPolicy | default "Delete" }}
{{- else }}
reclaimPolicy: Delete
{{- end }}
{{- if $val.allowedTopologies }}
{{- if kindIs "string" $val.allowedTopologies }}
allowedTopologies: {{ tpl $val.allowedTopologies $ }}
{{- else }}
allowedTopologies: {{ $val.allowedTopologies | toYaml | nindent 0 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
